### ISSUE TITLE
returning iHH0/iHH1 values for right vs. left?

### ISSUE THREAD

**Issue by josephvitti** [szpiech/selscan#12]
Currently, selscan returns iHH for each variant at a site, as well as the unstandardized iHS. In calculating these former two values, selscan presumably first calculates iHH to the left and the right for each variant. Is it possible to return these intermediate values (iHH0_left, iHH0_right, iHH1_left, iHH_right) as well?

**Comment by tomkinsc** [comment]
This is present in the commits contained in pull request #13.

**Comment by szpiech** [comment]
Excellent, thank you.
