### ISSUE TITLE
Include latest version of norm in tagged release?

### ISSUE THREAD

**Issue by tomkinsc** [szpiech/selscan#15]
It looks like the latest version of selscan supporting the `--ihs-detail` flag made it into the [1.1.0-tagged release](https://github.com/szpiech/selscan/releases/tag/1.1.0), but the version of `norm` which will tolerate the detailed ten-column ihs data did not. Would it be possible to include the latest version of [norm](https://github.com/szpiech/selscan/blob/master/src/norm.cpp) in a new tagged release?

**Comment by szpiech** [comment]
Oh, thanks for catching that.  I'll be able to recompile the binaries and update in a few days.
