### ISSUE TITLE
Plot iHs from selscan

### ISSUE THREAD

**Issue by plxsas** [szpiech/selscan#19]
Dear Zachary A Szpiech,

Can you please help me with this matter?

I did manage to run the test of signature of selection using selscan and now I am trying to make a plot.

I am trying to use the r script you provide in src folder. Is this how it should be run, please?

plotHaplotypes(example.ihs.out) of course after running the function first.

I am looking forward to hearing from you.

Thanks

**Comment by szpiech** [comment]
The R script that I have posted (and which is completely undocumented, I admit) will plot haplotype structure  surrounding a particular locus.  It was something I wrote to play around with output from using the --ehh flag (it will use those inscrutable and undocumented *.colormap files) and isn't meant to be used with iHS output. If you wish to plot iHS scores you should just load the output file into R (i.e. ```data<-read.table("example.ihs.out")```), and plot as usual.

If you want to check out what the plotHaplotypes() does, first source the script ("run the function") and then try ```plotHaplotypes("example.ehh.Locus4077.out")``` with the example data provided.
