### ISSUE TITLE
Core dump when using --nsl in norm

### ISSUE THREAD

**Issue by le-marquis** [szpiech/selscan#25]
Using the --nsl flag in norm causes the program to crash when the normalisation starts. Using the --ihs flag on the same data works:

ERROR:  No such file or directoryterminate called after throwing an instance of 'int'
Aborted (core dumped)

**Comment by bfraser8** [comment]
I'm having the same problem and would love to know if there's a difference between the norm procedure for the different stats.
Thanks!

**Comment by szpiech** [comment]
Thanks for finding this. The nSL and iHS normalization routines are identical, so you can use ```--ihs``` in the mean time to normalize nSL data. I'll fix ```--nsl``` ASAP.

**Comment by szpiech** [comment]
Okay, this ought to be fixed now with norm v1.2.1.
