### ISSUE TITLE
Error when using physical map sorted based on physical position and ID

### ISSUE THREAD

**Issue by vguerracanedo** [szpiech/selscan#26]
I'm running into a silly problem. My physical map file has repetitive physical positions with unique IDs. The data is sorted based on <physical position> and then in <ID>. Example at the end of the message. 

When I try to use iHS, I get the following problem: ERROR: Variant physical position must be strictly increasing.
	rs201044430 216605 comes after	rs112068709 216605
My data is already sorted so that 'rs201044430 216605' comes after 'rs112068709 216605'. So I'm not sure what to do differently. 

Best, 
Vanessa

---
Sample file
---
7 rs28527214 216426 216426
7 rs66644650 216512 216512
7 rs148463803 216515 216515
7 rs28485819 216569 216569
7 rs28498692 216570 216570
7 rs112068709 216605 216605
7 rs201044430 216605 216605
7 rs188651719 216660 216660
7 rs193275413 216662 216662
7 rs137869704 216672 216672
7 rs139968177 216735 216735 
---

**Comment by szpiech** [comment]
Hi Vanessa,

Sorry for the delay in getting back to you. At the moment selscan can only handle biallelic variants, and so when multiple variants are reported at the same physical position it will throw this error, although I can see how it can be a confusing message. I think your best bet would be to filter these two sites from your dataset. I hope this helps!

-Zach

**Comment by vguerracanedo** [comment]
Hi Zach, 
Thank you for responding. As you noted, removing the entries with repeated physical positions did the trick. 
Best,
V

**Comment by szpiech** [comment]
So my first thought is that you should request the site by rsid and not position. Please try `selscan --ehh rs139397353 --vcf chr22.vcf.gz --map plink22.map --maf 0.0001 --out test.txt` and see if that works. Admittedly that doesn't seem to be a terribly useful error message that you got. I'll have to make it more informative. Please let me know if this, at least, solves your problem.

**Comment by vs4223** [comment]
Hi Zach,

Many thanks for getting back to me. Unfortunately this does not solve the issue. I still get the exact same error. Also would using IDs not prove an issue for de novo variants that have not been assigned an ID?

**Comment by szpiech** [comment]
Sorry for the delay in getting back to you.

Yes, I think that I should modify the lookup scheme to allow for rsid or genomic position. I typically assign variants without an rsid a temporary id based on the chromosome and position, but I forget this isn't what everyone does.

Are you using a publicly accessible vcf file? I would like to try to reproduce this problem.

**Comment by szpiech** [comment]
Physical map duplicated locations are now allowed, and statistics that are integrated over a map can directly use physical positions with `--pmap`.

**Comment by TimothyCiesielski** [comment]
Hi Zach,

I am new to Selscan and I am having a similar issue.  I have been able to get nSL output for one chromosome but when I attempt to run whole genomes, I get this error: 

ERROR: Variant physical position must be monotonically increasing.
        2:10610:G:A 10610 appears after 1:248945650:C:G 248945650

example code:
selscan --nsl --vcf nameofVCFfile.vcf   --out selscannSLresults

It looks like --pmap is not available for nSL . . . any thoughts?

Thanks in advance for your help (and for making Selscan user friendly),
Tim 

😃

**Comment by szpiech** [comment]
Hi Tim,

You’ll have to separate your files by chromosome and run each separately.
You can then normalize them together with norm. Let me know if you have
more issues.

Zachary

**Comment by TimothyCiesielski** [comment]
Thanks Zach - I appreciate the help on this.
Tim

**Comment by malteze2024** [comment]
Hello! Please tell me how to solve the problem with the sheep genome map file.
If the map file is sorted by genetic position, the program generates a physical position error and vice versa. Of the 26 chromosomes, only 12 are processed without errors.
The initial map file was generated through GenomeStudio.

`for reg in $(seq 1 26) ; do selscan --xpehh --vcf phasedRMMrenchr$reg.vcf.gz --vcf-ref phasedDMrenchr$reg.vcf.gz --map MAP_sorted$reg.map --threads 12 --out 2xpEhhcheap$reg; done`
selscan v2.0.0
Opening phasedRMMrenchr1.vcf.gz...
Loading 108 haplotypes and 61259 loci...
Opening phasedDMrenchr1.vcf.gz...
Loading 106 haplotypes and 61259 loci...
Opening MAP_sorted1.map...
Loading map data for 61259 loci
ERROR: Variant genetic position must be monotonically increasing.
        oar3_OAR1_101700644 122.639 appears after       oar3_OAR1_101688882 122.64

`for reg in $(seq 1 26) ; do selscan --xpehh --vcf phasedRMMrenchr$reg.vcf.gz --vcf-ref phasedDMrenchr$reg.vcf.gz --map 2MAP_sorted$reg.map --threads 12 --out 2xpEhhcheap$reg; done`
selscan v2.0.0
Opening phasedRMMrenchr1.vcf.gz...
Loading 108 haplotypes and 61259 loci...
Opening phasedDMrenchr1.vcf.gz...
Loading 106 haplotypes and 61259 loci...
Opening MAP_sorted1.map...
Loading map data for 61259 loci
ERROR: Variant physical position must be monotonically increasing.
        OAR19_64803054.1 204694 appears after   DU281551_498.1 315497

With best regards, Lesya

**Comment by szpiech** [comment]
Hello,

From my perspective, the important question is why are there sites with map
positions out of order relative to the physical positions. In principle
this should be impossible, so I would investigate why this seemed to
happen. I could see this possibly resulting from a liftover of a genetic
map between genome builds, for example.

However, the simplest solution would be to drop one of the two offending
sites from your data. If one of the two sites has low MAF, you might as
well drop that one, as selscan would filter it out anyway.

Hope this helps,

Zachary

**Comment by malteze2024** [comment]
Thank you for such a quick response!
Apparently, I will still have to use the --pmap option. 
Does using a physical map have a big impact on my results? There are 600k SNP in my file.

**Comment by szpiech** [comment]
Hello,

Well, generally they should be comparable, although you may find slightly
more extreme scores in regions of low recombination. You could also choose
to use xp-nsl, which doesn't use either distance, although it may still
have similar properties. On the whole, I don't think it is too much of a
concern.

Zachary

**Comment by drsancho** [comment]
hello sir

i m working on cow genome and need to run selscan for ihh12. I have phased the the 29 chromosomes into a single vcf file. I am running the command 
selscan --ihh12 --vcf xyzz.vcf --map abc.map --out final

the error it is showing is variant physical position must be monotonically increasing. i am just starting my studies in bioinformatics. can you guide me how to navigate through it.

thank you

sanchit

**Comment by drsancho** [comment]
![selscan problem](https://github.com/szpiech/selscan/assets/167742045/ebdd5f39-62b2-4cf4-9765-e199c37ceece)

i have tried sorting also, it gives the similar error using command sort -nk 4 xyz.map > xyz1.map

**Comment by szpiech** [comment]
Hello,

You will need to split your vcfs by chromosome in order to run it through
selscan.

-Zachary

**Comment by drsancho** [comment]
okay sir

**Comment by szpiech** [comment]
Hello,

This error means that your positions are out of order in your file. You
need to either put them in order or remove the sites that are out of order.

-Zachary
