### ISSUE TITLE
Request: alternate version of XP-EHH for better performance on incomplete sweeps

### ISSUE THREAD

**Issue by lasugden** [szpiech/selscan#27]
The current implementation of XP-EHH uses the formula from Sabeti _et al._ (2007) for EHH, with (N choose 2) in the denominator. There is an alternate version that can be found in the supplement of Wagh _et al._ 2012 (http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0044751#s6) (supplementary note here: http://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0044751.s011&type=supplementary), and I wonder if you would be willing to implement it as an optional flag? The difference is in the denominator of EHH: (N_A choose 2) + (N_a choose 2) where N_A and N_a are the numbers of chromosomes with each of the alleles at the core SNP. The benefit of this definition is that the denominator is the number of pairwise comparisons that could possibly be identical given the alleles at the core SNP, instead of just the total number of possible pairwise comparisons. This makes it much more sensitive for ongoing sweeps in which the beneficial allele has not yet swept through most of the population (and so the number of pairwise comparisons is greater than the number of those comparisons that could possibly result in a match). I have already implemented this in my forked repository by adding in a few lines in selscan-main.cpp if this is helpful. Thanks!!

**Comment by szpiech** [comment]
Could you initiate a pull-request? I'll look it over and work on merging it. Cheers!

**Comment by lasugden** [comment]
I just initiated a pull request -- let me know if I can make things more clear!

Thanks so much!

**Comment by szpiech** [comment]
Two years later, but it's finally in the master branch.

**Comment by lasugden** [comment]
I noticed! I am extremely grateful, thank you!
