### ISSUE TITLE
understand the out file of selscan

### ISSUE THREAD

**Issue by Lee211** [szpiech/selscan#35]
The out file of ihs includes the several columns: ID, pos, '1' freq, ihh1, ihh0, unstandardized iHS. i want to know which allele was selected when iHS (the last column) is positive/negative? I do not encode the input file using 0 for ancestral allele and 1 for derived allele. I guess positive iHS represents the allele encoded by '1' was selected, it is may be ancestral (encode by '1') or derived allele (encode by '1'). Is my understand true ???

**Comment by szpiech** [comment]
I recommend reading through the manual section 4 and Szpiech and Hernandez (2014), where this information is explained. These are available in the github repository. In general when using selscan, more positive values suggest longer and higher frequency haplotypes surrounding the '1' allele, more negative values suggest the same for haplotypes surrounding the '0' allele.
