### ISSUE TITLE
about the ehh output file

### ISSUE THREAD

**Issue by simengYu** [szpiech/selscan#37]
The out file of ehh includes 'physicalPos' 'geneticPos' '1ehh' '0ehh',but my data has 5 columns .I want to konw what the last column of data means. My out file like this:
-7622   -0.007622       0.790850        0.346774        0.239184
-7398   -0.007398       0.790850        0.356855        0.243265
-1961   -0.001961       0.790850        0.502016        0.302041
-1143   -0.001143       1.000000        0.502016        0.328163
-549    -0.000549       1.000000        0.514113        0.333061
-153    -0.000153       1.000000        0.824597        0.458776
0       0.000000        1.000000        1.000000        0.124898
667     0.000667        1.000000        0.612903        0.373061
890     0.000890        1.000000        0.580645        0.360000

**Comment by szpiech** [comment]
Sorry, I seem to have failed to identify this column in the manual. The last column is the EHH of the entire sample.
