### ISSUE TITLE
Why the XP-EHH process skip the first around 100 SNPs

### ISSUE THREAD

**Issue by Victor0122** [szpiech/selscan#38]
Hi
I am running the SELSCAN for a while. Then I jest recognized that if I run the default setting of selscan, the output result that will skip the first 100 SNPs, I dont know why this happen? Do you have any suggestions?

**Comment by szpiech** [comment]
If the computation reached the end of a chromosome or a large gap before reaching the ```--cutoff``` it will throw out that score. If you wish to retain these scores, you can use the ```--trunc-ok``` option.
