### ISSUE TITLE
Interpreting positive and negative XP-EHH values

### ISSUE THREAD

**Issue by melou219** [szpiech/selscan#39]
Hi there,

I wonder what the negative and positive XP-EHH values mean. In the original publication of Sabeti et al 2007, they state that positive values reflect recent selection in population A and negative values represent selection in the population B. In selscan, the input file are --hap and --ref: So would a negative EHH-value mean likely selection in the reference population?

Thanks for clarification.

And btw thank you for this great program!

Best wishes

**Comment by szpiech** [comment]
Yes, you are correct, negative values suggest the direction of the ‘’’—ref’’’ population. Thanks!
