### ISSUE TITLE
ihh12 norm file

### ISSUE THREAD

**Issue by ainacolovila** [szpiech/selscan#41]
Hi,
When normalizing iHH12 the given output has the header inserted in the first line: 

![image](https://user-images.githubusercontent.com/44291292/72332158-d34b5280-36b9-11ea-9636-df81c945c6a1.png)

Thank you in advanced,

Aina

**Comment by szpiech** [comment]
Can you try using selscan v1.2.0a and normalizing with norm v1.2.1a? These are available [here](https://github.com/szpiech/selscan/tree/master/bin).

**Comment by ainacolovila** [comment]
It works. Thank you so much!

Aina
