### ISSUE TITLE
 |iHS| >2 uses standardized iHS or unstandardized iHS?

### ISSUE THREAD

**Issue by weiwFu** [szpiech/selscan#42]
Hi

I want to know the extreme positive iHS or extreme negative iHS ( |iHS| >2) uses standardized iHS or unstandardized iHS?

--crit - val <double >: Set the critical value such that a SNP with | iHS| >
CRIT_VAL is marked as an extreme SNP. Default as in Voight et al.
Default : 2.00

Thank you in advance

Weiwei Fu

**Comment by szpiech** [comment]
Hello, it uses the standardized scores.
