### ISSUE TITLE
P-value calculation for xpehh

### ISSUE THREAD

**Issue by devenderarora** [szpiech/selscan#43]
Dear Sir,
I have performed **selscan --xpehh** for my data and found xpehh value from the repective program. I am interested in P-Value is there any way to calculate the same?

**Comment by szpiech** [comment]
Hello, 
After genome wide normalization, the scores are approximately distributed as a standard normal. One option is to treat the normalized scores as Z scores and compute a p-value from there.

**Comment by devenderarora** [comment]
Thankyou so much sir.
I did normalized the xpehh score and able to get p-value.
