### ISSUE TITLE
norm logfile errors 

### ISSUE THREAD

**Issue by mark-sutherland** [szpiech/selscan#44]
Hi Zachary,

When submitting my scripts for norm I keep getting the following error:
  
You have provided 3 output files for joint normalization.
ERROR: logfile No such file or directory

code:
./selscan-linux-1.3.0/norm --ihs --files ch1selscangm.ihs.out ch2selscangm.ihs.out ch5selscangm.ihs.out --bins 50
norm v1.3.0

I have tried using the --log option but still get the same error. The code was working previously and suddenly stopped. 

Many thanks 

Mark

**Comment by szpiech** [comment]
Hi there,

Did this start happening after updating to v1.3.0 or just out of the blue? There may be something weird going on with the local environment. I know this sounds basic, but have you ensured that you can write to the current working directory? Have you tried changing directory into the folder that contains it and executing from there? I think I've seen this happen once or twice, but it's never been clear why. Although I've often solved it by looking at those possible issues.

**Comment by mark-sutherland** [comment]
Hi Zachary, 

It turns out it was an environment problem, fixed by the IT team. 

Thanks for your help
