### ISSUE TITLE
Makefile issues

### ISSUE THREAD

**Issue by PhDMattyB** [szpiech/selscan#45]
Hi Folks, 

I am trying to get selscan up and running on our lab computer. Running Ubuntu through Windows as the Make command doesn't work in Windows. When I go to the src folder and use the make command I get this error: 

> collect2: error: 1d returned 1 exist status
> Makefile: 50 : recipe for target 'norm' failed
> make: *** [norm] Error 1

There is probably a simple fix for this but i wasn't sure what that would be. 
Any help would be greatly appreciated. 

-Matt

**Comment by szpiech** [comment]
Hmm, I've not used Ubuntu through Windows, and I don't really see an indication here why this failed. Have you tried making with `make -f Makefile.lin`?

**Comment by PhDMattyB** [comment]
Okay, I'll give it a go and report back. Thanks for the quick response!

-Matt

On Jun. 25, 2020 3:48 p.m., Zachary A Szpiech <notifications@github.com> wrote:

CAUTION: This email originated from outside of the University of Guelph. Do not click links or open attachments unless you recognize the sender and know the content is safe. If in doubt, forward suspicious emails to IThelp@uoguelph.ca


Hmm, I've not used Ubuntu through Windows, and I don't really see an indication here why this failed. Have you tried making with make -f Makefile.lin?

**Comment by PhDMattyB** [comment]
That worked perfectly, thanks so much for the help!

-Matt

On Jun. 25, 2020 3:48 p.m., Zachary A Szpiech <notifications@github.com> wrote:

CAUTION: This email originated from outside of the University of Guelph. Do not click links or open attachments unless you recognize the sender and know the content is safe. If in doubt, forward suspicious emails to IThelp@uoguelph.ca


Hmm, I've not used Ubuntu through Windows, and I don't really see an indication here why this failed. Have you tried making with make -f Makefile.lin?
