### ISSUE TITLE
Window size selection

### ISSUE THREAD

**Issue by devenderarora** [szpiech/selscan#46]
Dear Sir,
I am working with SNP data and we ran xp-ehh using selscan and it works smooth less. Currently, I am looking for a window size to rerun the same. Is there any way we can set window size to 5kb or so?
I will be grateful for any help in this regards.
Regards
Devender

**Comment by szpiech** [comment]
Hi there,

The only place that a window size pops up is when using norm to compute the percentage of extreme scores in a region. You can compute this with norm by passing the `--bp-win` flag, and you can change the size of the window to 5kb with `--winsize 5000`. Hope this helps.

**Comment by devenderarora** [comment]
Dear Sir,
I tried using --bp-win option as suggested. I am able to get output with <start> <end> <no of snps> <score> <some window size 5/100>
Although this works fine but now I am not able to get any P-value as suggested earlier with norm function in 5kb window file. Any suggestion on this part.

**Comment by szpiech** [comment]
I'm not sure I know what you are looking for, as xpehh is computed on a site by site basis. The only window option is when looking for clusters of extreme scores with `norm --bp-win`.
