### ISSUE TITLE
no standardized IHS output?

### ISSUE THREAD

**Issue by jkreinz** [szpiech/selscan#48]
Hi again Zack,

Sorry to bug you again but I've gone through the manual and the paper and am still looking for clarification.

The manual says `<locusID > <physicalPos > <’1’ freq > <ihh1 > <ihh0 > < unstandardized iHS >` is the format of the iHS output. From the paper and manual, I would have expected a standardized iHS column as well. Is this not explicity output by selscan?

Thanks!
Julia

**Comment by szpiech** [comment]
For normalization, you will want to use the `norm` program. Since all contigs/chrs should be normalized together, you should pass all of them to `norm` at the same time. e.g. `norm --ihs --files chr1.ihs.out chr2.ihs.out ... chrN.ihs.out`
