### ISSUE TITLE
Unable to reproduce example file scores

### ISSUE THREAD

**Issue by aastha-v** [szpiech/selscan#49]
Hello!

I am running selscan on Ubuntu 18 LTS. I am unable to get the same iHS values as the example.ihs.out file here. My log looks like this:

../src/./selscan --ihs --hap example.hap --map example.map --out test.example --threads 10 
v1.3.0
Calculating  iHS.
Input filename: example.hap
Map filename: example.map
Output file: test.example.ihs.out
Threads: 10
Scale parameter: 20000
Max gap parameter: 200000
EHH cutoff value: 0.05
Alt flag set: no
--skip-low-freq set. Removing all variants < 0.05.
Removed 2750 low frequency variants.
WARNING: Reached chromosome edge before EHH decayed below 0.05. Skipping calculation at Locus5
WARNING: Reached chromosome edge before EHH decayed below 0.05. Skipping calculation at Locus2
WARNING: Reached chromosome edge before EHH decayed below 0.05. Skipping calculation at Locus18
WARNING: Reached chromosome edge before EHH decayed below 0.05. Skipping calculation at Locus13
WARNING: Reached chromosome edge before EHH decayed below 0.05. Skipping calculation at Locus34
WARNING: Reached chromosome edge before EHH decayed below 0.05. Skipping calculation at Locus39
WARNING: Reached chromosome edge before EHH decayed below 0.05. Skipping calculation at Locus4

while the scores in both files look like this:

test.example.ihs.out:Locus188	108585	0.3	0.0263938	0.020108	0.118132
test.example.ihs.out:Locus1880	1168591	0.14	0.33279	0.0168633	1.29523
test.example.ihs.out:Locus1881	1169264	0.06	0.998161	0.0138525	1.85767
test.example.ihs.out:Locus1882	1170860	0.12	0.327554	0.0168659	1.28827
test.example.ihs.out:Locus1883	1172545	0.24	0.146858	0.0156062	0.9736
test.example.ihs.out:Locus1884	1173195	0.06	1.12876	0.0113121	1.99906
test.example.ihs.out:Locus1885	1173749	0.12	0.327569	0.0127553	1.40961
test.example.ihs.out:Locus1887	1174701	0.34	0.0489453	0.0206153	0.375522
test.example.ihs.out:Locus1888	1174777	0.34	0.0489453	0.0206153	0.375522
test.example.ihs.out:Locus1889	1175022	0.06	0.562215	0.00961574	1.76692

example.ihs.out:Locus188	108585	0.3	0.0173648	0.0150461	0.143324
example.ihs.out:Locus1880	1168591	0.14	0.157038	0.0110095	2.65773
example.ihs.out:Locus1881	1169264	0.06	0.573633	0.0092492	4.12745
example.ihs.out:Locus1882	1170860	0.12	0.20044	0.010789	2.92199
example.ihs.out:Locus1883	1172545	0.24	0.0475636	0.0105927	1.5019
example.ihs.out:Locus1884	1173195	0.06	0.498914	0.00738917	4.21242
example.ihs.out:Locus1885	1173749	0.12	0.200548	0.00833627	3.18044
example.ihs.out:Locus1887	1174701	0.34	0.029491	0.00829141	1.26886
example.ihs.out:Locus1888	1174777	0.34	0.029491	0.00829141	1.26886
example.ihs.out:Locus1889	1175022	0.06	0.123439	0.00563158	3.08735

The same applies to other scores like XP-EHH, though I'm primarily interested in iHS.

The hap and map files I have downloaded have the same number of lines as here. 

How can I fix this?

**Comment by szpiech** [comment]
Hi there,

I generated those example files several years ago, and since then the program defaults have slightly changed. If you are getting output, this means the program is functioning.  Sorry for the confusion! I will have to update the example files to avoid this confusion in the future.

**Comment by aastha-v** [comment]
Thank you so much!
