### ISSUE TITLE
Could Selscan be faster?

### ISSUE THREAD

**Issue by fengyq** [szpiech/selscan#50]
Hi,
Thanks for this great software, but I found selscan is about >100 times slower than rehh and hapbin.  Could you update it and make it faster?

**Comment by szpiech** [comment]
To match hapbin, selscan will need a re-implementation of the data structures to store genotypes bitwise and a re-implementation of haplotype comparison computations to operate similarly. This level of re-writing is too time intensive for me these days, but I welcome contributions attempting it or students/postdocs willing to take on a major re-write of the code.

However, implementation of new statistics and maintenance updates will continue.

**Comment by fengyq** [comment]
Thanks for your great efforts, Looking forward to the new statistics.
