### ISSUE TITLE
normalize XP-nSL

### ISSUE THREAD

**Issue by yuxi-Hu** [szpiech/selscan#51]
Hi,

I'm currently trying to perform your new method XP-nSL on my data. I have normalized the results with non-overlapping windows of 20kb, and the command I used is  `norm --xpnsl --files hm_eas_cen_chr1.xpnsl.out --bp-win --min-snps 20 --winsize 20000`.
However I'm not sure what the results from column 4 to column 7 in the *.windows file represent. The manual describes it like this:

For XP stats:
<win start> <win end> <# scores in win> <frac scores **gt** threshold> <frac scores **lt** threshold> <approx percentile for **gt** threshold wins> <approx percentile for **lt** threshold wins> <max score> <min score>

I am a bit confused about the meaning of "gt" and "lt". Does the former one mean the positive scores, and the latter one mean negative scores?

The *.windows file I got is as follows:
1             20001   273     0.014652        0       100     5       2.15695 0.360257
20001   40001   259     0.169884        0       100     5       2.90022 0.62959
40001   60001   250     0.868              0        5        5       4.83393 1.36376
60001   80001   239     1                      0        1         100    3.38311 2.06651
80001   100001  235     0.595745       0       5        100     3.63697 0.842613

Thanks in advance!

**Comment by szpiech** [comment]
Hi there, sorry for the confusion. "gt" == "greater than" and "lt" == "less than", and you are correct these essentially correspond to extreme positive and extreme negative score stats.
