### ISSUE TITLE
some question for XP-EHH calculate

### ISSUE THREAD

**Issue by Axolotl233** [szpiech/selscan#52]
Hi, I used selscan to calculate xp-ehh recently, and I ran into two questions  

1). I did not get any useful result after step "norm" (almost all of window has 0 fracCrit value[column 4] in 'norm' program output). After check every file manual, i found some "big" xpehh value like (525.xxx,not equal in each file) in input file of "norm" program, and also found 'inf' in some site. i think it abnormal but i do not know what is wrong

because data size is big, i split iuput file by window, 
my comman line is:
$selscan --xpehh --hap $$hap2s[$i] --ref $$hap1s[$i] --map $$maps[$i] --out $out --threads $thread_xpehh
norm --xpehh --files *.xpeff --bp-win --winsize 10000 --min-snps 10

2). in the absence of a good quality recombination map, the recombination rate was assumed to be 1 cM (centiMorgan) per Mbp for genome, i don't know what effect on xp-ehh calculate.

I'm a new bee of poplutation genetics and can't solve it by my self, I would appreciate a lot if you provide some advice to me.

**Comment by szpiech** [comment]
Hi there,

Splitting these computations on the same contig/chromosome into windows is not generally recommended. You could conceivably do it with some careful thought, but simply splitting the genome into non-overlapping windows for computing xp-ehh would cause some biases in score computation around the window edges. This may be the reason why you see unusually large (>525) scores.

Asserting a constant recombination map is essentially the same as using physical distance (e.g. with `--pmap` flag), and is acceptable to do, although you may lose some ability to identify sweeps in regions with recombination hotspots and you may get higher scores in low recombination regions. You might also consider using the xp-nsl statistic, which does not require a recombination map and tends to run faster than xp-ehh.

**Comment by Axolotl233** [comment]
Hi,

Now i will try to run it again, and you can close this issue temporary. If I meet other question, i will ask again (hope not~)
Thank you very much for your advice.
