### ISSUE TITLE
Column Header info

### ISSUE THREAD

**Issue by vb-cscottg** [szpiech/selscan#53]
Hello, I just need information about the column header produced by norm --ihs. From parts of the manual and different questions, I can tell that it's 

WINSTART       WINSTOP.        N.SNPS.WINDOW  probably.fraction.gt.threshold.        PERCENTILE       ????   

What is the last column that ranges in values from 1-4? Is the fourth column interpreted correctly as being the fraction greater than critical threshold? Apologies ahead of time if this is written elsewhere.

COMMAND RUN:
norm --ihs --bp-win --files ./chr1.ihs.out ./chr2.ihs.out ./chr3.ihs.out ./chr4.ihs.out ./chr5.ihs.out ./chr6.ihs.out ./chr7.ihs.out ./chr
8.ihs.out ./chr9.ihs.out ./chr10.ihs.out ./chr11.ihs.out ./chr12.ihs.out ./chr13.ihs.out ./chr14.ihs.out ./chr15.ihs.out ./chr16.ihs.out .
/chr17.ihs.out ./chr18.ihs.out ./chr19.ihs.out ./chr20.ihs.out ./chr21.ihs.out ./chr22.ihs.out

OUTPUT
[ rsltSelscan]$ head chr2.ihs.out.100bins.norm.100kb.windows
1	        100001	15	0	                100	1
100001	200001	302	0.013245	        100	2
200001	300001	180	0.00555556	100	2

**Comment by szpiech** [comment]
Hi there,

Sorry this is confusing, compounded by some typos in the README. The fourth column is the frac greater than the critical threshold and the last column is the `max |iHS|` in the window. Although I just noticed that this was coded as an `int` for some reason, so until I change that it is giving the `floor[max |iHS|]`.

**Comment by vb-cscottg** [comment]
Thank you so much for the speedy response and clarification!
