### ISSUE TITLE
Are these methods included in selscan suitable for multiple allelic makers?

### ISSUE THREAD

**Issue by woaishiye** [szpiech/selscan#55]
Dear author:
    I am working on detecting the selection signals with a kind of marker that has more than two alleles, so I am wondering if there exists a method that is suitable for this kind of marker. Below are the example lines for my marker in vcf format (please ignore the allele frequency).
1	4485	BLK_1_4485_26943	0	1,2,3,4,5,6,7,8	.	.	.	GT	0|0	1|1	2|2	2|2	6|6	1|1	7|7	5|5	6|6	0|0	8|8	8|8	7|7	6|6	7|7	0|0	0|0	0|0	6|6	0|0	4|4	6|6	5|5	1|1	0|0	1|1	1|1	4|4	2|2	7|7	7|7
1	75460	BLK_1_75460_88853	0	1,2,3,4,5	.	.	.	GT	0|0	1|1	2|2	2|2	0|0	1|1	0|0	1|1	2|2	0|0	3|3	0|0	0|0	2|2	0|0	0|0	0|0	0|0	2|2	0|0	4|4	0|0	1|1	1|1	0|0	1|1	1|1	5|5	5|5	3|3	4|4

This kind of marker, which we call it SNPLDB, was  constructed form whole genome SNPs data basing on the LD (D') value between SNPs. (Gabriel SB, Schaffner SF, Nguyen H, Moore JM, Roy J, Blumenstiel 
B, Higgins J, DeFelice M, Lochner A, Faggart M, Liu-Cordero SN, Rotimi C, Adeyemo A, Cooper R, Ward R, Lander ES, Daly MJ, Altshuler D (2002) The structure of haplotype blocks in the human genome. Science 296:2225–2229 )
Looking forward to your reply, any help will be appreciated.

**Comment by szpiech** [comment]
Hi there,

Unfortunately, for the time being, selscan is written to only accept biallelic loci.
