### ISSUE TITLE
norm xpehh output format

### ISSUE THREAD

**Issue by YuanwenGuo** [szpiech/selscan#57]
Hello,

I am trying to get normalized xpehh values within windows using commands:
norm --xpehh --files $input --bp-win --winsize 20000

The output has 9 columns, could you please provide header information for each column? Which one is the normalized xpehh? The output is as follows:
1       20001   105     0       0       1       100     0.427604        -1.47963
20001   40001   355     0       0.0478873       100     1       0.726029        -2.30077
40001   60001   949     0       0       1       100     1.21741 -1.75812
60001   80001   532     0       0       100     100     1.76434 -1.32259
80001   100001  667     0       0       100     100     1.85594 -0.384881
100001  120001  488     0       0       100     100     1.85094 -1.61615
120001  140001  529     0.0415879       0.00378072      100     100     2.14336 -2.10125
140001  160001  404     0       0       100     100     0.782917        -1.62801
160001  180001  571     0       0       100     100     1.74265 -1.46968
180001  200001  598     0       0       100     100     1.70662 -0.920458

Thank you,
Yuanwen

**Comment by YuanwenGuo** [comment]
Sorry I just realized there are descriptions about xpehh norm results in the manual pdf. It looks like I can find max, min and etc in the table, but is there a normalized value for the window which could be used for plotting?

Thank you for the help,
Yuanwen

**Comment by szpiech** [comment]
Hi there, I think your best option for a single value per window is to plot the max or min, depending on which target population you're interested in.

**Comment by YuanwenGuo** [comment]
Thank you for the suggestion!

Best,
Yuanwen
