### ISSUE TITLE
Ancestral / derived alleles for iHS and nSL

### ISSUE THREAD

**Issue by Daluser1** [szpiech/selscan#69]
Dear Szpiech,

I am working on a dataset on which there is no information on the ancestral/derived state to encode 0 / 1 variants for analyses. I only have information from one population. I used ref/alt coding to calculate the statistics (iHS and nSL). However, I am not sure if these results are correct or not? I would sincerely appreciate any advice on it.

**Comment by szpiech** [comment]
Hi there,

Yes you can use ref/alt coding. You will lose a small amount of power
without the anc/der information, but the statistics work perfectly well
when using ref/alt.

-Zachary

Le lun. 17 janv. 2022 à 8:37 AM, Daluser1 ***@***.***> a
écrit :

**Comment by Daluser1** [comment]
Dear Szpiech,

Thank you very much for your prompt reply. I have one more question:
The ref/alt is by default being used by software? or, it should be specified in the command line?

**Comment by szpiech** [comment]
It is the default (there is no other option).  Hope this helps!

Zachary

Le lun. 17 janv. 2022 à 9:24 AM, Daluser1 ***@***.***> a
écrit :

**Comment by Daluser1** [comment]
Thanks Zachary for your reply. I appreciate it!
