### ISSUE TITLE
 EHH Statistics

### ISSUE THREAD

**Issue by Daluser1** [szpiech/selscan#70]
Dear Szpiech,

I am working on a dataset on which there is no information on the ancestral/derived state to encode 0 / 1 variants for analyses. EHH statistics does not require the definition of ancestral alleles? So, is it can be used in a situation where the ancestral/derived state is unknown?

Thanks in Advance!

**Comment by szpiech** [comment]
Hello,

Yes you can use the EHH statistic without ancestral/derived information.
The haplotype decay curves will be based on the ref/alt allele haplotypes
at the focal SNP.

-Zachary

Le jeu. 17 févr. 2022 à 1:12 AM, Daluser1 ***@***.***> a
écrit :

**Comment by Daluser1** [comment]
Thank you so much for your response. I appreciate it!
