### ISSUE TITLE
EHH output interpretation

### ISSUE THREAD

**Issue by sadiexiaoyu** [szpiech/selscan#72]
Hi, Szpiech,
thank you for the cool software.
I am running EHH to get the EHH decay plot, and I have several questions about the output files.
First of all, how can I use the output file .colormap draw the EHH decay plot? 
Secondly, what does the output file **.out**  mean? For example,
-99968	-99968.000000	0.122342	0.015415	0.016067
-99802	-99802.000000	0.122342	0.015415	0.016067
-99801	-99801.000000	0.122342	0.015415	0.016067
-99775	-99775.000000	0.122342	0.015415	0.016067
-99734	-99734.000000	0.122342	0.015415	0.016067
-99649	-99649.000000	0.122342	0.015415	0.016067
-99617	-99617.000000	0.122342	0.015415	0.016067
-99475	-99475.000000	0.122342	0.015415	0.016067
-99312	-99312.000000	0.122342	0.015415	0.016067
-99190	-99190.000000	0.122342	0.015415	0.016067
-99142	-99142.000000	0.122342	0.015415	0.016067
-99065	-99065.000000	0.122342	0.015415	0.016067
-98972	-98972.000000	0.122342	0.015415	0.016067
-98746	-98746.000000	0.122342	0.015415	0.016067
-98557	-98557.000000	0.122342	0.015415	0.016067
-98472	-98472.000000	0.122342	0.015415	0.016067
-98350	-98350.000000	0.122342	0.015415	0.016067
-97959	-97959.000000	0.122342	0.015415	0.016067
-97735	-97735.000000	0.122342	0.015415	0.016067
-97444	-97444.000000	0.122342	0.015415	0.016067
-97184	-97184.000000	0.122342	0.015415	0.016067
-97096	-97096.000000	0.122342	0.015415	0.016067
-97038	-97038.000000	0.122342	0.015415	0.016067

In the selscan manual, it says that the output file of EHH include physicalPos, geneticPos, 1 EHH, 0EHH. But it seems not the case...did I miss anything?
Looking forward to your reply! Thanks!

**Comment by szpiech** [comment]
Hi there,

The file you've quoted here is the file you can use to generate the decay curves. The manual is a little out of date, sorry about that. The columns refer to 

physicalPos relative to core SNP, geneticPos relative to core SNP, 1 EHH, 0EHH, total EHH (all 0 and 1 haplotypes together)

So you get negative values for the positions when the location is upstream of the core snp, and positive values when the position is downstream of the core.

Hope this helps,

Zach

**Comment by sadiexiaoyu** [comment]
Thank you very much for the quick reply!
