### ISSUE TITLE
Working with large number of SNPs and few different haplotypes

### ISSUE THREAD

**Issue by RamGonzalez** [szpiech/selscan#77]
Hi professor Szpiech,

Thank you for such an awesome and simple to use tool for computing selection statistics! I have a couple of questions on how should I go about using selscan when having a large number of SNPs but a low number of different haplotypes:

I'm calculating iHS, nSL and XPEHH on different whole genome data sets (around 15-25 samples per data set). I noticed an flag in the manual for rehh called _freqbin_ for iHS when approaching a similar issue: 

> "_freqbin_: Size of the bins to standardize log(iHH_A/iHH_D). (...) If set to 0, standardization is performed considering each observed frequency as a discrete frequency class (useful in case of a large number of markers and few different haplotypes)"

1. Is there a similiar option or strategy to this on selscan?

2. So far, in iHS for example, I'm normalizing using: `norm --ihs --bins 20 --files [all .ihs.out files per chr]` but I'm hesitant to use 20 bins since almost half of them come out empty, should I lower the number of bins? maybe down to 1?

Best,
Ram

**Comment by szpiech** [comment]
Hello,

Thanks for the kind words. I haven’t implemented this precise feature in
norm, but you can arrive at the same thing by setting qbins to a large
number. There will be a lot of empty bins but since they are empty they
won’t affect anything.

Hope this helps,

Zachary

Le mer. 30 mars 2022 à 1:16 PM, Ram Gonzalez ***@***.***> a
écrit :

**Comment by szpiech** [comment]
Hello,

I meant you should set —bins to a high number, not qbins. Sorry for any
confusion!

Zachary

Le mer. 30 mars 2022 à 4:54 PM, Zachary Szpiech ***@***.***> a
écrit :

**Comment by RamGonzalez** [comment]
Hello,

Thanks for your reply! I'll run some tests with different and bigger bin sizes as per your suggestion. 

Best,
Ram

**Comment by szpiech** [comment]
Hi Ram,

To be clear, setting —bins higher creates more bins not larger bins. So if
you set it high enough you will necessarily force one bin per observed
allele frequency.

Zach

Le jeu. 31 mars 2022 à 1:54 PM, Ram Gonzalez ***@***.***> a
écrit :

**Comment by RamGonzalez** [comment]
Hi professor Szpiech!

So far I've looked at iHS results with the option --bins set to 20, 100, 500 and 1000. The biggest difference I've seen is between 20 and all of the other ones, with slightly higher |iHS| values when using more bins, and just a bit more well defined peaks of signals (less noise reduction). Although I was expecting to see a more noticeable reduction in noise and maybe a decrease on the value of the statistic. 

With 25 individuals and normalizing with all previously tested bin values I get an |iHS| around 15, which I'm thinking could be instead due to the low number of samples or the nature of the statistic being used. Good practices in normalization like the one you suggested are essential nonetheless, I'm thinking on going over 1000 bins and see how that changes the results.

Thanks again for your follow-up. Best,
Ram
