### ISSUE TITLE
Support for VCF files

### ISSUE THREAD

**Issue by tomkinsc** [szpiech/selscan#9]
It would be helpful to have direct support for VCF files, with tabix indices

**Comment by szpiech** [comment]
I've included basic VCF support (without tabix) in the latest commit 7af301ded3fc8a23631bda239c925f52ee8c3f0d.

Tabix support may have to wait a bit, but I hope this is satisfactory in the meantime.

**Comment by tomkinsc** [comment]
This is terrific. Thanks, Zachary! 
I'll likely need to do some pre-filtering on the VCF files I have, but at least this way I can drop records rather than reform all of the data to tped format.

One question: How does selscan handle VCF records with multi-allelic variants? (As are found for SNPs in the phase 3 1000 Genomes dataset, for example.)
