### ISSUE TITLE
Setting ehh-win and max-extend in XP-EHH calculation

### ISSUE THREAD

**Issue by AliceIob** [szpiech/selscan#91]
Hi, 

I am trying to calculate XP-EHH, and, considering my data, and I expect EHH to decay very slowly with bp-distance from the core SNP. For this reason, I want to constrain as less as possible the calculation of the statistics. 
I was looking at the manual, and I don't understand how I should combine these 2 options :
**--ehh-win** <int> _to define for a single EHH computation the maximum extension in base pairs from
the query locus. Default is 100, 000 bp._
**--max-extend** <int> _Use --max-extend <int> to set an additional stopping condition for iHS and XP-EHH computations. If
the EHH decay curve has extended MAX EXTEND bp away from the core without reaching the ehh
decay cutoff, truncate the curve here and integrate. Default is 1, 000, 000 bp; set ≤ 0 for no restriction._

If I understand correctly, even if I set max-extend to no restriction (<=0)  for integrating EHH, the size of genomic window in which EHH is computed will still be dependent on ehh-win, is this right?
Is there a way to allow for EHH calculation from the core locus without restriction (i.e. up to the bp where EHH reaches 0.05)? Or shall I simply select a very very big number to reach the same effect? 

Thank you in advance

**Comment by szpiech** [comment]
Hello,

You will want to set —max-extend to 0, and this will set no restriction.
Keep in mind that this may also result in fewer sites with xpehh scores
near chromosome ends and large gaps.

The —ehh-win option is only when calculating with the —ehh flag. Sorry for
the confusion!

-Zachary

Le mer. 1 févr. 2023 à 6:58 AM, AliceIob ***@***.***> a
écrit :
